[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = { version = "0.7.0", features = ["html_reports"] }


[[bench]]
name = "add_bench"
harness = false


[[bench]]
name = "multiply_bench"
harness = false

